//
//  ToothConditionsEnums.h
//  Dental-iPad
//
//  Created by Sanch0 on 5/25/15.
//  Copyright (c) 2015 Finnet Limited. All rights reserved.
//

#ifndef Dental_iPad_ToothConditionsEnums____FILEEXTENSION___
#define Dental_iPad_ToothConditionsEnums____FILEEXTENSION___

//CONDITION TYPE
#define TOOTH_CONDITION_TYPE_START  @"TOOTHCONDITION_START"
#define TOOTH_CONDITION_TYPE_RESULT @"TOOTHCONDITION_RESULT"



/* --------- TOOTH CONDITION CODES -------- */
#define TOOTH_CONDITION_DECAY_DISTAL        @"TOOTH_CONDITION_DECAY_DISTAL"
#define TOOTH_CONDITION_DECAY_FACIAL        @"TOOTH_CONDITION_DECAY_FACIAL"
#define TOOTH_CONDITION_DECAY_MESIAL        @"TOOTH_CONDITION_DECAY_MESIAL"
#define TOOTH_CONDITION_DECAY_FACIAL5       @"TOOTH_CONDITION_DECAY_FACIAL5"
#define TOOTH_CONDITION_DECAY_OCLUSAL       @"TOOTH_CONDITION_DECAY_OCLUSAL"
#define TOOTH_CONDITION_DECAY_INCISAL       @"TOOTH_CONDITION_DECAY_INCISAL"
#define TOOTH_CONDITION_DECAY_LINGUAL       @"TOOTH_CONDITION_DECAY_LINGUAL"
#define TOOTH_CONDITION_DECAY_LINGUAL5      @"TOOTH_CONDITION_DECAY_LINGUAL5"
#define TOOTH_CONDITION_DECAY_BUCCAL        @"TOOTH_CONDITION_DECAY_BUCCAL"
#define TOOTH_CONDITION_DECAY_BUCCAL5       @"TOOTH_CONDITION_DECAY_BUCCAL5"

#define TOOTH_CONDITION_AMALGAM_DISTAL        @"TOOTH_CONDITION_AMALGAM_DISTAL"
#define TOOTH_CONDITION_AMALGAM_FACIAL        @"TOOTH_CONDITION_AMALGAM_FACIAL"
#define TOOTH_CONDITION_AMALGAM_MESIAL        @"TOOTH_CONDITION_AMALGAM_MESIAL"
#define TOOTH_CONDITION_AMALGAM_FACIAL5       @"TOOTH_CONDITION_AMALGAM_FACIAL5"
#define TOOTH_CONDITION_AMALGAM_OCLUSAL       @"TOOTH_CONDITION_AMALGAM_OCLUSAL"
#define TOOTH_CONDITION_AMALGAM_INCISAL       @"TOOTH_CONDITION_AMALGAM_INCISAL"
#define TOOTH_CONDITION_AMALGAM_LINGUAL       @"TOOTH_CONDITION_AMALGAM_LINGUAL"
#define TOOTH_CONDITION_AMALGAM_LINGUAL5      @"TOOTH_CONDITION_AMALGAM_LINGUAL5"
#define TOOTH_CONDITION_AMALGAM_BUCCAL        @"TOOTH_CONDITION_AMALGAM_BUCCAL"
#define TOOTH_CONDITION_AMALGAM_BUCCAL5       @"TOOTH_CONDITION_AMALGAM_BUCCAL5"

#define TOOTH_CONDITION_PROVISIONAL_RESTORATION_DISTAL        @"TOOTH_CONDITION_PROVISIONAL_RESTORATION_DISTAL"
#define TOOTH_CONDITION_PROVISIONAL_RESTORATION_FACIAL        @"TOOTH_CONDITION_PROVISIONAL_RESTORATION_FACIAL"
#define TOOTH_CONDITION_PROVISIONAL_RESTORATION_MESIAL        @"TOOTH_CONDITION_PROVISIONAL_RESTORATION_MESIAL"
#define TOOTH_CONDITION_PROVISIONAL_RESTORATION_FACIAL5       @"TOOTH_CONDITION_PROVISIONAL_RESTORATION_FACIAL5"
#define TOOTH_CONDITION_PROVISIONAL_RESTORATION_OCLUSAL       @"TOOTH_CONDITION_PROVISIONAL_RESTORATION_OCLUSAL"
#define TOOTH_CONDITION_PROVISIONAL_RESTORATION_INCISAL       @"TOOTH_CONDITION_PROVISIONAL_RESTORATION_INCISAL"
#define TOOTH_CONDITION_PROVISIONAL_RESTORATION_LINGUAL       @"TOOTH_CONDITION_PROVISIONAL_RESTORATION_LINGUAL"
#define TOOTH_CONDITION_PROVISIONAL_RESTORATION_LINGUAL5      @"TOOTH_CONDITION_PROVISIONAL_RESTORATION_LINGUAL5"
#define TOOTH_CONDITION_PROVISIONAL_RESTORATION_BUCCAL        @"TOOTH_CONDITION_PROVISIONAL_RESTORATION_BUCCAL"
#define TOOTH_CONDITION_PROVISIONAL_RESTORATION_BUCCAL5       @"TOOTH_CONDITION_PROVISIONAL_RESTORATION_BUCCAL5"

#define TOOTH_CONDITION_NONMETALLIC_RESTORATION_DISTAL        @"TOOTH_CONDITION_NONMETALLIC_RESTORATION_DISTAL"
#define TOOTH_CONDITION_NONMETALLIC_RESTORATION_FACIAL        @"TOOTH_CONDITION_NONMETALLIC_RESTORATION_FACIAL"
#define TOOTH_CONDITION_NONMETALLIC_RESTORATION_MESIAL        @"TOOTH_CONDITION_NONMETALLIC_RESTORATION_MESIAL"
#define TOOTH_CONDITION_NONMETALLIC_RESTORATION_FACIAL5       @"TOOTH_CONDITION_NONMETALLIC_RESTORATION_FACIAL5"
#define TOOTH_CONDITION_NONMETALLIC_RESTORATION_OCLUSAL       @"TOOTH_CONDITION_NONMETALLIC_RESTORATION_OCLUSAL"
#define TOOTH_CONDITION_NONMETALLIC_RESTORATION_INCISAL       @"TOOTH_CONDITION_NONMETALLIC_RESTORATION_INCISAL"
#define TOOTH_CONDITION_NONMETALLIC_RESTORATION_LINGUAL       @"TOOTH_CONDITION_NONMETALLIC_RESTORATION_LINGUAL"
#define TOOTH_CONDITION_NONMETALLIC_RESTORATION_LINGUAL5      @"TOOTH_CONDITION_NONMETALLIC_RESTORATION_LINGUAL5"
#define TOOTH_CONDITION_NONMETALLIC_RESTORATION_BUCCAL        @"TOOTH_CONDITION_NONMETALLIC_RESTORATION_BUCCAL"
#define TOOTH_CONDITION_NONMETALLIC_RESTORATION_BUCCAL5       @"TOOTH_CONDITION_NONMETALLIC_RESTORATION_BUCCAL5"

#define TOOTH_CONDITION_METALLIC_RESTORATION_DISTAL        @"TOOTH_CONDITION_METALLIC_RESTORATION_DISTAL"
#define TOOTH_CONDITION_METALLIC_RESTORATION_FACIAL        @"TOOTH_CONDITION_METALLIC_RESTORATION_FACIAL"
#define TOOTH_CONDITION_METALLIC_RESTORATION_MESIAL        @"TOOTH_CONDITION_METALLIC_RESTORATION_MESIAL"
#define TOOTH_CONDITION_METALLIC_RESTORATION_FACIAL5       @"TOOTH_CONDITION_METALLIC_RESTORATION_FACIAL5"
#define TOOTH_CONDITION_METALLIC_RESTORATION_OCLUSAL       @"TOOTH_CONDITION_METALLIC_RESTORATION_OCLUSAL"
#define TOOTH_CONDITION_METALLIC_RESTORATION_INCISAL       @"TOOTH_CONDITION_METALLIC_RESTORATION_INCISAL"
#define TOOTH_CONDITION_METALLIC_RESTORATION_LINGUAL       @"TOOTH_CONDITION_METALLIC_RESTORATION_LINGUAL"
#define TOOTH_CONDITION_METALLIC_RESTORATION_LINGUAL5      @"TOOTH_CONDITION_METALLIC_RESTORATION_LINGUAL5"
#define TOOTH_CONDITION_METALLIC_RESTORATION_BUCCAL        @"TOOTH_CONDITION_METALLIC_RESTORATION_BUCCAL"
#define TOOTH_CONDITION_METALLIC_RESTORATION_BUCCAL5       @"TOOTH_CONDITION_METALLIC_RESTORATION_BUCCAL5"

#define TOOTH_CONDITION_FRACTURE_CROWN          @"TOOTH_CONDITION_FRACTURE_CROWN"
#define TOOTH_CONDITION_FRACTURE_ROOT          @"TOOTH_CONDITION_FRACTURE_ROOT"
#define TOOTH_CONDITION_METALLIC_CROWN          @"TOOTH_CONDITION_METALLIC_CROWN"
#define TOOTH_CONDITION_METAL_CERAMIC_CROWN          @"TOOTH_CONDITION_METAL_CERAMIC_CROWN"
#define TOOTH_CONDITION_METAL_FREE_CROWN          @"TOOTH_CONDITION_METAL_FREE_CROWN"
#define TOOTH_CONDITION_TEMPORAL_CROWN          @"TOOTH_CONDITION_TEMPORAL_CROWN"
#define TOOTH_CONDITION_DESTROYED_CROWN          @"TOOTH_CONDITION_DESTROYED_CROWN"

#define TOOTH_CONDITION_FRACTURE_ROOT          @"TOOTH_CONDITION_FRACTURE_ROOT"
#define TOOTH_CONDITION_TURN          @"TOOTH_CONDITION_TURN"
#define TOOTH_CONDITION_SHIFT_X          @"TOOTH_CONDITION_SHIFT_X"
#define TOOTH_CONDITION_SHIFT_Y          @"TOOTH_CONDITION_SHIFT_Y"
#define TOOTH_CONDITION_SHIFT_Z          @"TOOTH_CONDITION_SHIFT_Z"
#define TOOTH_CONDITION_RESIDUAL_ROOT          @"TOOTH_CONDITION_RESIDUAL_ROOT"
#define TOOTH_CONDITION_TOOTH_ACHE          @"TOOTH_CONDITION_TOOTH_ACHE"
#define TOOTH_CONDITION_MOBILITY_GRADE          @"TOOTH_CONDITION_MOBILITY_GRADE"
#define TOOTH_CONDITION_FURCATION_GRADE          @"TOOTH_CONDITION_FURCATION_GRADE"
#define TOOTH_CONDITION_CALCULUS_GRADE          @"TOOTH_CONDITION_CALCULUS_GRADE"

#define TOOTH_CONDITION_VENEER @"TOOTH_CONDITION_VENEER"
#define TOOTH_CONDITION_TOOTH_STATUS @"TOOTH_CONDITION_TOOTH_STATUS"
#define TOOTH_CONDITION_BANDING @"TOOTH_CONDITION_BANDING"
#define TOOTH_CONDITION_FISSURE_SEALANT @"TOOTH_CONDITION_FISSURE_SEALANT"
#define TOOTH_CONDITION_OCCLUSAL_REDUCTION @"TOOTH_CONDITION_OCCLUSAL_REDUCTION"








//TOOTH STATUS
#define TOOTHSTATUS_NORMAL @"TOOTHSTATUS_NORMAL"
#define TOOTHSTATUS_IMPLANT @"TOOTHSTATUS_IMPLANT"
#define TOOTHSTATUS_ABSENT @"TOOTHSTATUS_ABSENT"
#define TOOTHSTATUS_BRIDGE @"TOOTHSTATUS_BRIDGE"


//CALCULUS, MOBILITY, FURCATION GRADES
#define TOOTHGRADE_NONE @"TOOTHGRADE_NONE"
#define TOOTHGRADE_GRADE1 @"TOOTHGRADE_GRADE1"
#define TOOTHGRADE_GRADE2 @"TOOTHGRADE_GRADE2"
#define TOOTHGRADE_GRADE3 @"TOOTHGRADE_GRADE3"
#define TOOTHGRADE_GRADE4 @"TOOTHGRADE_GRADE4"

//TOOTH ACHE
#define TOOTH_ACHE_NONE @"ToothAche_None"
#define TOOTH_ACHE_SENSITIVE @"ToothAche_Sensitive"
#define TOOTH_ACHE_PULPITIS @"ToothAche_Pulpitis"
#define TOOTH_ACHE_ACUTE_PERIAPICAL @"ToothAche_Acute_Periapical"
#define TOOTH_ACHE_CHRONIC_PERIAPICAL @"ToothAche_Chronic_Periapical"


//SHIFT X
#define TOOTHSHIFT_NONE @"TOOTHSHIFT_NONE"
#define TOOTHSHIFT_MESIALIZED @"TOOTHSHIFT_MESIALIZED"
#define TOOTHSHIFT_DISTALIZED @"TOOTHSHIFT_DISTALIZED"
//SHIFT Y

#define TOOTHSHIFT_FACIALIZED @"TOOTHSHIFT_FACIALIZED"
#define TOOTHSHIFT_LINGUALIZED @"TOOTHSHIFT_LINGUALIZED"

//SHIFT Z

#define TOOTHSHIFT_INTRUDED @"TOOTHSHIFT_INTRUDED"
#define TOOTHSHIFT_EXTRUDED @"TOOTHSHIFT_EXTRUDED"


//TOOTH TURN
#define TOOTHTURN_NONE                  @"TOOTHTURN_NONE"
#define TOOTHTURN_CLOCKWISE             @"TOOTHTURN_CLOCKWISE"
#define TOOTHTURN_COUNTERCLOCKWISE      @"TOOTHTURN_COUNTERCLOCKWISE"


#define TRANSACTION_PRICE_SOURCE_INSURANCE @"TRANSACTION_PRICE_SOURCE_INSURANCE"
#define TRANSACTION_PRICE_SOURCE_COMPANY @"TRANSACTION_PRICE_SOURCE_COMPANY"

#endif
